### ISSUE TITLE
grommunio-index-run.sh: Insecure way of passing password to mysql(1)

### ISSUE THREAD

**Issue by robert-scheck** [grommunio/grommunio-index#3]
As of writing [`grommunio-index-run.sh`](https://github.com/grommunio/grommunio-index/blob/e735128c5f41595e93ee6999f05dc8fbb7fe224f/grommunio-index-run.sh) parses `/etc/gromox/mysql_adaptor.cfg` and constructs arguments to `mysql` – including the password (aside of this the current implementation may break with passwords containing spaces, semicolons or other characters interpreted by the bash; https://github.com/grommunio/grommunio-index/pull/2 tries to address this partially).

https://mariadb.com/kb/en/mysql-command-line-client/ (more or less a web version of the `man` page) says:
> Specifying a password on the command line should be considered insecure. You can use an option file to avoid giving the password on the command line.

The [MySQL 8.0 Reference Manual](https://dev.mysql.com/doc/refman/8.0/en/) goes into the details with § [6.1.2.1 End-User Guidelines for Password Security](https://dev.mysql.com/doc/refman/8.0/en/password-security-user.html) regarding `-p`:

> This is convenient *but insecure*. On some systems, your password becomes visible to system status programs such as `ps` that may be invoked by other users to display command lines. MySQL clients typically overwrite the command-line password argument with zeros during their initialization sequence. However, there is still a brief interval during which the value is visible. Also, on some systems this overwriting strategy is ineffective and the password remains visible to `ps`. (SystemV Unix systems and perhaps others are subject to this problem.)

While I expect a system running grommunio to be sealed system (= not to be used by regular shell users), this can not be expected in general, nor does it seem to be required by the documentation. This insecure way of passing a password to `mysql` might be treated as security flaw, e.g. [CWE-214: Invocation of Process Using Visible Sensitive Information](https://cwe.mitre.org/data/definitions/214.html). Note that I don't treat this as overly critical, because of the before mentioned behavior of MySQL clients.

My recommendation is to parse `/etc/gromox/mysql_adaptor.cfg` and to write a temporary configuration file (often known as `.my.cnf`) that could be passed using `--defaults-file=<path to temporary configuration file>` to `mysql`. Of course that temporary configuration file needs proper permissions and should be deleted after usage.

**Comment by grammmike** [comment]
Thanks. See 4ebe9ad.
