### ISSUE TITLE
/etc/gromox/mysql_adaptor.cfg: Permission denied

### ISSUE THREAD

**Issue by robert-scheck** [grommunio/grommunio-index#6]
According to https://github.com/grommunio/grommunio-documentation/issues/23#issuecomment-2128050557, only the `grommunio-admin-api.service` uses the system user `grommunio`, so that the (restrictive) permissions `root:gromoxcf` and `0640` for `/etc/gromox/mysql_adaptor.cfg` should fit when one doesn't plan to use the AAPI to change the configuration.

However, when using grommunio-index-1.0.2.gb782c51-22.1, it turns out that this unfortunately doesn't seem to be correct:

```
$ systemctl status grommunio-index.service 
× grommunio-index.service - Fulltext search index regeneration
     Loaded: loaded (/usr/lib/systemd/system/grommunio-index.service; static)
     Active: failed (Result: exit-code) since Thu 2024-05-23 23:53:23 CEST; 3s ago
TriggeredBy: ● grommunio-index.timer
    Process: 1625 ExecStart=/usr/bin/grommunio-index -Aq (code=exited, status=1/FAILURE)
   Main PID: 1625 (code=exited, status=1/FAILURE)
        CPU: 54ms

May 23 23:53:23 mail systemd[1]: Starting Fulltext search index regeneration...
May 23 23:53:23 mail grommunio-index[1625]: /etc/gromox/mysql_adaptor.cfg: Permission denied
May 23 23:53:23 mail systemd[1]: grommunio-index.service: Main process exited, code=exited, status=1/FAILURE
May 23 23:53:23 mail systemd[1]: grommunio-index.service: Failed with result 'exit-code'.
May 23 23:53:23 mail systemd[1]: Failed to start Fulltext search index regeneration.
$ 
```

And when looking to this failure more closely using `strace`:

```
$ strace --timestamps -s 4096 -fff /usr/bin/grommunio-index -Aq 2>&1 | grep -e mysql_adaptor -e execve -e getuid -e setgroups -e setuid
23:59:01 execve("/usr/bin/grommunio-index", ["/usr/bin/grommunio-index", "-Aq"], 0xffffcf7e7a48 /* 31 vars */) = 0
23:59:01 openat(AT_FDCWD, "/etc/gromox/mysql_adaptor.cfg", O_RDONLY) = 3
23:59:01 setgroups(3, [988, 190, 987])  = 0
23:59:01 getuid()                       = 0
23:59:01 setuid(989)                    = 0
23:59:01 execve("/usr/bin/grommunio-index", ["/usr/bin/grommunio-index", "-Aq"], 0xfffffbe35500 /* 31 vars */) = 0
23:59:01 openat(AT_FDCWD, "/etc/gromox/mysql_adaptor.cfg", O_RDONLY) = -1 EACCES (Permission denied)
23:59:01 write(2, "/etc/gromox/mysql_adaptor.cfg: Permission denied\n", 49/etc/gromox/mysql_adaptor.cfg: Permission denied
$ 
```

```
$ id grommunio 
uid=989(grommunio) gid=989(grommunio) groups=989(grommunio),190(systemd-journal),988(groweb),987(gromox)
$ 
```

[`grommunio-index.cpp:1058`](https://github.com/grommunio/grommunio-index/blob/b782c514b8d2a754d11b62ea01b5028db6e6b6e8/grommunio-index.cpp#L1058) confirms above.

So, not only the `grommunio-admin-api.service` uses the system user `grommunio`, but also `grommunio-index` (and it currently even depends on these permissions to work). Thus from my point of view either the behaviour of `grommunio-index` or the documentation at [admin/manual_core.rst#permissions](https://github.com/grommunio/grommunio-documentation/blob/master/admin/manual_core.rst#permissions) should be adapted.

**Comment by jengelh** [comment]
1.0-5-g175d11d
